# © 2024-2026 ETH Zurich
# Original author: Milos Katanic
# Simulation-only fork & maintainer: Maitraya Avadhut Desai
#
# Licensed under the GNU General Public License v3.0 or later;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#
#     https://www.gnu.org/licenses/gpl-3.0.en.html
#
# This software is distributed "AS IS", WITHOUT WARRANTY OF ANY KIND,
# express or implied. See the License for specific language governing
# permissions and limitations under the License.
#
# Simulation-only fork of PowerDynamicEstimator
# (https://doi.org/10.5905/ethz-1007-842); dynamic state estimation removed.
# For inquiries, contact: mdesai@ethz.ch

"""Parameter metadata for the builder's forms, introspected from the models.

Every device class declares its parameters, defaults, descriptions and
mandatory fields at construction time (``_params``, ``_setpoints``,
``_descr``, ``_mand``, ``_param_sentinels``), so a parameter form can be
generated by instantiating the class with the chosen strategies and reading
them back. The defaults shown in the GUI are therefore the core's own, and a
model gaining a parameter shows up here without GUI changes. User-registered
device classes (:func:`hermess.register`) resolve exactly like shipped ones.
"""

from __future__ import annotations

import importlib
import math
import pkgutil
from dataclasses import dataclass, field

#: Strategy axes selectable on a device line, with their registries.
STRATEGY_AXES = {
    "avr": ("hermess.devices.avr", "AVR_REGISTRY"),
    "governor": ("hermess.devices.governor", "GOVERNOR_REGISTRY"),
    "pss": ("hermess.devices.pss", "PSS_REGISTRY"),
    "shaft": ("hermess.devices.shaft", "SHAFT_REGISTRY"),
    "filter": ("hermess.devices.inverter_filter", "FILTER_REGISTRY"),
    "angle": ("hermess.devices.inverter_angle", "ANGLE_REGISTRY"),
    "voltage": ("hermess.devices.inverter_voltage", "VOLTAGE_REGISTRY"),
    "inner": ("hermess.devices.inverter_inner", "INNER_REGISTRY"),
    "pll": ("hermess.devices.inverter_pll", "PLL_REGISTRY"),
}

_SM_AXES = ("avr", "governor", "pss", "shaft")
_INVERTER_AXES = ("filter", "angle", "voltage", "inner", "pll")

#: Instance attribute holding each axis's strategy object.
_AXIS_ATTRS = {
    "avr": "_avr",
    "governor": "_governor",
    "pss": "_pss",
    "shaft": "_shaft",
    "filter": "_filter",
    "angle": "_angle",
    "voltage": "_voltage",
    "inner": "_inner",
    "pll": "_pll",
}


@dataclass
class ParamMeta:
    """What a generated form needs to render one entry kind."""

    kind: str
    params: "dict[str, str]" = field(default_factory=dict)  #: name -> default, as file text
    descriptions: "dict[str, str]" = field(default_factory=dict)
    mandatory: "list[str]" = field(default_factory=list)
    sentinels: "dict[str, str]" = field(default_factory=dict)  #: NaN param -> fallback
    strategy_axes: "list[str]" = field(default_factory=list)  #: applicable axes
    #: axis -> registry name of the strategy the model uses when none is
    #: selected; an axis that defaults to no strategy at all is absent.
    strategy_defaults: "dict[str, str]" = field(default_factory=dict)


def format_default(value) -> str:
    """A default value as it would appear in the system file."""
    if value is None:
        return ""
    if isinstance(value, float):
        if math.isnan(value):
            return ""  # sentinel: resolved from another parameter at build time
        return repr(value)
    return str(value)


def strategy_choices(axis: str) -> "list[str]":
    """Selectable strategy names of one axis (shipped + user-registered)."""
    module_name, registry_name = STRATEGY_AXES[axis]
    registry = getattr(importlib.import_module(module_name), registry_name)
    return list(registry)


def find_device_class(kind: str):
    """The device class named ``kind``, from the user registry or the shipped
    modules; None when it does not exist."""
    from hermess.registry import DEVICE_REGISTRY

    if kind in DEVICE_REGISTRY:
        return DEVICE_REGISTRY[kind]
    package = importlib.import_module("hermess.devices")
    for module_info in pkgutil.iter_modules(package.__path__):
        try:
            module = importlib.import_module(f"hermess.devices.{module_info.name}")
        except Exception:
            continue
        obj = getattr(module, kind, None)
        if isinstance(obj, type):
            return obj
    return None


def buildable_device_kinds() -> "list[str]":
    """Class names offered in the builder palette: every shipped or registered
    device class that takes a bus and is instantiable with defaults."""
    from hermess.registry import DEVICE_REGISTRY

    kinds = []
    package = importlib.import_module("hermess.devices")
    for module_info in pkgutil.iter_modules(package.__path__):
        if module_info.name == "device":
            continue  # base classes and grid primitives, not placeable devices
        try:
            module = importlib.import_module(f"hermess.devices.{module_info.name}")
        except Exception:
            continue
        for name, obj in vars(module).items():
            if (
                isinstance(obj, type)
                and obj.__module__ == module.__name__
                and _instantiable(obj)
            ):
                kinds.append(name)
    kinds += [k for k in DEVICE_REGISTRY if k not in kinds]
    return sorted(set(kinds))


def _instantiable(cls) -> bool:
    try:
        instance = cls()
    except Exception:
        return False
    return "bus" in getattr(instance, "_mand", [])


def _registry_key(axis: str, strategy) -> str:
    """The registry name of a strategy instance (its class name as fallback)."""
    module_name, registry_name = STRATEGY_AXES[axis]
    registry = getattr(importlib.import_module(module_name), registry_name)
    cls = type(strategy)
    if registry.get(cls.__name__) is cls:
        return cls.__name__
    for key, value in registry.items():
        if value is cls:
            return key
    return cls.__name__


def _strategy_defaults(cls, axes: "list[str]") -> "dict[str, str]":
    """What each axis resolves to when nothing is selected on the file line."""
    try:
        instance = cls()
    except Exception:
        return {}
    defaults = {}
    for axis in axes:
        strategy = getattr(instance, _AXIS_ATTRS[axis], None)
        if strategy is not None:
            defaults[axis] = _registry_key(axis, strategy)
    return defaults


def _axes_for(instance) -> "list[str]":
    if hasattr(instance, "_filter"):
        return list(_INVERTER_AXES)
    if hasattr(instance, "_avr") or hasattr(instance, "avr"):
        return list(_SM_AXES)
    return []


def device_meta(kind: str, strategies: "dict[str, str] | None" = None) -> "ParamMeta | None":
    """Form metadata for the device class ``kind`` with the given strategy
    selection ({axis: registry name}); None when the class is unknown or not
    instantiable with that selection."""
    from hermess.utils.data_loader import _strategy_instances

    cls = find_device_class(kind)
    if cls is None:
        return None
    strategies = {k: v for k, v in (strategies or {}).items() if v}
    try:
        kwargs = _strategy_instances(
            avr_type=strategies.get("avr"),
            governor_type=strategies.get("governor"),
            pss_type=strategies.get("pss"),
            shaft_type=strategies.get("shaft"),
            filter_type=strategies.get("filter"),
            angle_type=strategies.get("angle"),
            voltage_type=strategies.get("voltage"),
            inner_type=strategies.get("inner"),
            pll_type=strategies.get("pll"),
        )
        instance = cls(**kwargs)
    except Exception:
        return None

    defaults = {**instance._params, **instance._setpoints}
    defaults.pop("bus_i", None)  # line-style keys never apply to a device
    defaults.pop("bus_j", None)
    axes = _axes_for(instance)
    return ParamMeta(
        kind=kind,
        params={name: format_default(value) for name, value in defaults.items()},
        descriptions=dict(instance._descr),
        mandatory=[m for m in instance._mand if m != "bus"],  # bus set by the canvas
        sentinels=dict(getattr(instance, "_param_sentinels", {})),
        strategy_axes=axes,
        strategy_defaults=_strategy_defaults(cls, axes),
    )


def line_meta() -> ParamMeta:
    from hermess.devices.device import Line
    from hermess.gui.sysdoc import LINE_DEFAULTS

    instance = Line()
    params = {
        name: LINE_DEFAULTS.get(name, format_default(value))
        for name, value in instance._params.items()
        if name not in ("bus_i", "bus_j")
    }
    return ParamMeta(kind="Line", params=params, descriptions=dict(instance._descr))


def businit_meta() -> ParamMeta:
    from hermess.devices.device import BusInit

    instance = BusInit()
    params = {
        name: format_default(value)
        for name, value in instance._data.items()
        if name not in ("bus", "u")
    }
    return ParamMeta(kind="BusInit", params=params, descriptions=dict(instance._descr))


def disturbance_fields() -> "dict[str, tuple[list[str], list[str]]]":
    """Per event type, the (required, optional) field names beyond ``type``,
    introspected from the core's own event specification so the editor can
    never drift from what :meth:`Disturbance.add` accepts."""
    from hermess.devices.device import Disturbance

    return {
        typ: (["time", *required], list(optional))
        for typ, (required, optional) in Disturbance._EVENT_FIELDS.items()
    }


def disturbance_field_meaning(name: str) -> str:
    """The core's one-line explanation (with units) of one event field."""
    from hermess.devices.device import Disturbance

    return Disturbance._FIELD_MEANING.get(name, "")


def disturbance_example(typ: str) -> str:
    """The core's example file line for one event type."""
    from hermess.devices.device import Disturbance

    return Disturbance._EVENT_EXAMPLES.get(typ, "")


def disturbance_defaults() -> "dict[str, str]":
    from hermess.devices.device import Disturbance

    instance = Disturbance()
    return {
        name: format_default(value)
        for name, value in instance._params.items()
        if name != "u"
    }
